### ISSUE TITLE
No shared folder available

### ISSUE THREAD

**Issue by keremnymn** [facebookresearch/deit#100]
Hello, I'm trying to train a model on my custom dataset on Colab, but this error prevents me from doing so:

`!python /content/deit/run_with_submitit.py --model deit_base_patch16_384 --batch-size 32 --finetune https://dl.fbaipublicfiles.com/deit/deit_base_patch16_224-b5f2ef4d.pth --input-size 384 --use_volta32 --nodes 2 --lr 5e-6 --weight-decay 1e-8 --epochs 30 --min-lr 5e-6 --data-path /content/abcde`

Error:

```
Traceback (most recent call last):
  File "/content/deit/run_with_submitit.py", line 126, in <module>
    main()
  File "/content/deit/run_with_submitit.py", line 85, in main
    args.job_dir = get_shared_folder() / "%j"
  File "/content/deit/run_with_submitit.py", line 36, in get_shared_folder
    raise RuntimeError("No shared folder available")
RuntimeError: No shared folder available
```
I just couldn't understand what I was doing wrong. Sorry if this is an obvious one but I couldn't solve it.

**Comment by molocule** [comment]
The part of the code that is throwing the error seems to be this:

```
def get_shared_folder() -> Path:
    user = os.getenv("USER")
    if Path("/checkpoint/").is_dir():
        p = Path(f"/checkpoint/{user}/experiments")
        p.mkdir(exist_ok=True)
        return p
    raise RuntimeError("No shared folder available")
```

Do you have the `/checkpoint/ ` directory? Maybe try making that and see if it works?

**Comment by keremnymn** [comment]
Okay I modified that function and created my own shared folder and solved this thanks to @molocule

**Comment by aliguran** [comment]
> Okay I modified that function and created my own shared folder and solved this thanks to @molocule

Hi Kerem, how did you solve this problem? Could you explain a bit more or put your modified function?
