### ISSUE TITLE
Colab Failure

### ISSUE THREAD

**Issue by mosicr** [facebookresearch/deit#101]
import timm ( 2nd cell ) fails with:
----> 6 from torch._six import container_abcs
      7 
      8 

ImportError: cannot import name 'container_abcs' from 'torch._six' (/usr/local/lib/python3.7/dist-packages/torch/_six.py)

**Comment by keremnymn** [comment]
Try using this installation:

```
!git clone https://github.com/facebookresearch/deit.git
!pip install timm -upgrade
!pip install git+https://github.com/rwightman/pytorch-image-models.git
!pip install submitit
```

**Comment by molocule** [comment]
seems to be this issue maybe? https://github.com/pytorch/pytorch/issues/51959

**Comment by dskkato** [comment]
`timm==0.3.2` requires torch version less than 1.9. Perhaps colab's PyTorch version is current latest 1.9. So you may need to PyTorch version in colab as follows:

```
!pip install torch==1.8.1 torchvision==0.9.1 torchaudio===0.8.1
```

and restart Colab

ref: [How To downgrade Torch Version for Google Colab](https://stackoverflow.com/questions/61273244/how-to-downgrade-torch-version-for-google-colab)

See also [this issue](https://github.com/Rayicer/TransFuse/pull/1)
