### ISSUE TITLE
Repeated augmentation setting when training cait model

### ISSUE THREAD

**Issue by anthonytmh** [facebookresearch/deit#104]
Thank you for sharing your interesting work. When training CAIT model for 400 epochs, does the repeated augmentation still keep at 3 as in DEIT 300 epochs?

**Comment by TouvronHugo** [comment]
Hi @anthonytmh ,
Thank you for your question,
No we have not changed the parameter of repeated augmentation but it may be sub-optimal.
Best,
Hugo
