### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by wj51** [facebookresearch/deit#107]
I only have one GPU , so is it  available to  distillation training? In the case of only one GPU card, how to run run_with_submitit.py ？

**Comment by TouvronHugo** [comment]
Hi @wj51 ,
Thanks for your message,
Yes, is it available but I don't know if you can use a big enough batch size.
With one GPU you can run the code with submitit but I think the code needs to be adapted a bit. It's easier to run it with  main.py in this case.
Best,
Hugo
