### ISSUE TITLE
Question regarding similarity of class token and distillation token

### ISSUE THREAD

**Issue by pmgautam** [facebookresearch/deit#111]
I am not able to figure out the similarity between the class token and distillation token. In the first sentence, the average cosine similarity is given 0.06 and in the second sentence 0.93 at last layer. Is 0.06 the similarity at the input level and 0.93 at the final layer? If not, can someone explain the differences between these two similarity scores? The text is given below for reference. Thanks in advance!

_the average cosine similarity between these tokens equal to 0.06. As the class and distillation embeddings are computed at each layer, they gradually become more similar through the network, all the way through the last layer at which their similarity is high (cos=0.93), but still lower than 1._

**Comment by TouvronHugo** [comment]
Hi @pmgautam,
Thanks for your question, 
The first one is the cosine similarity between the class and distillation tokens (before they are modified by Self-Attention). the  second one is the cosine similarity at the end of the network.
Best,
Hugo
