### ISSUE TITLE
How to train ResMLP with lamb

### ISSUE THREAD

**Issue by Andrew-Zhu** [facebookresearch/deit#112]
Since lamb is not implemented in the official PyTorch, Can we use FusedLAMB in apex.optimizers.fused_lamb to train ResMLP?

**Comment by TouvronHugo** [comment]
Yes of course, this is the one used in the timm library

**Comment by Andrew-Zhu** [comment]
Thanks for your reply.

**Comment by Andrew-Zhu** [comment]
What is your version of apex?

**Comment by TouvronHugo** [comment]
I have tested different versions, I think you can use the last one without any problem
Best,
Hugo
