### ISSUE TITLE
About setting the hyper-parameters in training ResMLP 

### ISSUE THREAD

**Issue by Andrew-Zhu** [facebookresearch/deit#113]
- In readme, crop-ratio is set as 0.9.

```
def get_test_transforms(input_size):
    mean, std = [0.485, 0.456, 0.406],[0.229, 0.224, 0.225]  
    transformations = {}  
    Rs_size=int(input_size/0.9)  
    transformations= transforms.Compose(  
        [transforms.Resize(Rs_size, interpolation= 3),  
         transforms.CenterCrop(input_size),  
         transforms.ToTensor(),  
         transforms.Normalize(mean, std)])  
    return transformations
```

In dataset.py, 

```
if resize_im:
       size = int((256 / 224) * args.input_size)
       t.append(
           transforms.Resize(size, interpolation=3),  # to maintain same ratio w.r.t. 224 images
       )
       t.append(transforms.CenterCrop(args.input_size))
```

Do we need to modify `(256 / 224) * args.input_size` as `args.input_size /0.9` in both training and testing?

- How to set Stochastic Depth as 0.05?

- How to set FP16 as False ?

Thanks!

**Comment by TouvronHugo** [comment]
Hi @Andrew-Zhu ,
Thanks for your questions,
- No you have to just change this in testing
- with the `--dop-path` flag
- Just by replacing `torch.cuda.amp.autocast()` by `torch.cuda.amp.autocast(enabled=False)`
Best,
Hugo
