### ISSUE TITLE
Folding Affine Layers in the cross-patch sublayer of resMLP

### ISSUE THREAD

**Issue by markgrobman** [facebookresearch/deit#114]
In the resMLP paper it is stated that Affine layers ca be folded during inference. While this can be done for the cross-channel sub-layer, I don't see a way to do it in the cross-patch sublayer since each patch is multiplied by different factors where for folding we would need it to be the same factors for each patch. Is there a trick i'm missing?

**Comment by TouvronHugo** [comment]
Hi @markgrobman ,
No, what you say is correct.
Best,
Hugo
