### ISSUE TITLE
If the model with distillation will be released?

### ISSUE THREAD

**Issue by xiaohu2015** [facebookresearch/deit#12]

**Comment by TouvronHugo** [comment]
Hi @xiaohu2015 
Thank you for your question.
It should be added in the next repo update.
Best,
Hugo

**Comment by xiaohu2015** [comment]
Thanks

**Comment by d-li14** [comment]
@TouvronHugo Hi, may I know your next repo update schedule? Thanks for your great effort!

**Comment by TouvronHugo** [comment]
Hi @d-li14 ,
I hope this week or next week. 
We try to do our best to do the update as soon as possible ;)
Best,
Hugo
