### ISSUE TITLE
what should I change to able to use the pretrained Deit on my data set with resolution of 750,184

### ISSUE THREAD

**Issue by Oussamab21** [facebookresearch/deit#121]
Hi I have a data that can be represented as images of 750*184, I was wondering what are the changes that I should do in order to be able to train this using the Deit model ?
thanks in advance

**Comment by TouvronHugo** [comment]
Hi @Oussamab21 ,
Thanks for your question,
It is necessary to modify the code to take into account  non square images.
For example, you need to redefine PatchEmbed.
Best,
Hugo
