### ISSUE TITLE
CaiT-12 LayerScale Init

### ISSUE THREAD

**Issue by collinmccarthy** [facebookresearch/deit#122]
Hello, quick question. The default `init_scale` value is 1e-4, with the larger models explicitly specifying 1e-5 and 1e-6. In the paper you report results for 12-layer versions, but state the `init_scale` value should be 0.1 for "up to depth 18". Did you mean to say 1e-4 for "up to depth 18"? 

Essentially, what should be the `init_scale` value for a 12-layer model to reproduce the results from the paper? I'm referring to the first row in Table 1 which reports 80.5% accuracy on ImageNet-1k with depth=12 using LayerScale.

Sorry if this is in the code / paper somewhere, I tried to find it but couldn't, and don't want to guess.

Thank you!
-Collin

**Comment by TouvronHugo** [comment]
Hi @collinmccarthy ,
Thanks for your question,
For 12-layer we use `initial_scale=0.1`,  `1e−5` for 24 and `1e-6` for 36.
Best,
Hugo
