### ISSUE TITLE
batchsize&&lr

### ISSUE THREAD

**Issue by Joseph-Lee-V** [facebookresearch/deit#125]
Hello,
I want to train Deit-Base on one nodes with 4 gpus with 24GB. How should I set the batch-size and lr? Thanks in advance!

**Comment by TouvronHugo** [comment]
Hi @Joseph-Lee-V,
Thanks for your question,
As detailed in the paper we use a linear adjustment of the lr according to the batch size but we are not sure that this is optimal.
Best,
Hugo

**Comment by Joseph-Lee-V** [comment]
Thanks for your reply!!! I have trained the Deit-Base with batchsize=128,lr=4.375e-4 at 7 gpus(namely linear adjustment), and the test_acc approach 80.8%.Maybe I should set the batchsize=146 and keep the lr=5e-4 to train at 7gpus?(146*7 is approximately equal to 16 * 64)

**Comment by westye1256599275** [comment]
Hi Joseph, I am trying to reproduce the deit-tiny, can you teach me how to do that? I follow the instruction in the github but i get lots of error which i don t know how to fix.

**Comment by westye1256599275** [comment]
If you are satisfied with teaching me this, can you leave your zoom email?

**Comment by westye1256599275** [comment]
I try to train deit-tiny by cifar 100 but the torch size is different from imagenet 
how can i change the torch size

RuntimeError: Error(s) in loading state_dict for VisionTransformer:
        size mismatch for head.weight: copying a param with shape torch.Size([1000, 192]) from checkpoint, the shape in current model is torch.Size([100, 192]).
        size mismatch for head.bias: copying a param with shape torch.Size([1000]) from checkpoint, the shape in current model is torch.Size([100]).

**Comment by Joseph-Lee-V** [comment]
> I try to train deit-tiny by cifar 100 but the torch size is different from imagenet how can i change the torch size
> 
> RuntimeError: Error(s) in loading state_dict for VisionTransformer: size mismatch for head.weight: copying a param with shape torch.Size([1000, 192]) from checkpoint, the shape in current model is torch.Size([100, 192]). size mismatch for head.bias: copying a param with shape torch.Size([1000]) from checkpoint, the shape in current model is torch.Size([100]).

emmmm, actually i haven't train Deit on CIFAR-100. If you want to train, you may not need "loading state_dict", right? Maybe "copying a param with shape torch.Size([1000, 192]) from checkpoint" means that u are using a pth file of imagenet.
