### ISSUE TITLE
Initial layerscale 

### ISSUE THREAD

**Issue by MenghaoGuo** [facebookresearch/deit#127]
Hi,  

Thanks for your great and helpful work. 

I want to know whether layerscale is sensitive to initial value ? 

Best, 
Menghao

**Comment by TouvronHugo** [comment]
Hi @MenghaoGuo,
Thanks for your question,
In our experiments, LayerScale was not very sensitive to small changes of value but large changes can have some impact. 
Best,
Hugo

**Comment by MenghaoGuo** [comment]
Thanks !
