### ISSUE TITLE
adding convertrs functions for onnx2keras 

### ISSUE THREAD

**Issue by LamyaMohaned** [facebookresearch/deit#129]
Hello,
Can you please implement converter functions that are not implemented in onnx2keras?
Here are the implemented converters: https://github.com/gmalivenko/onnx2keras/blob/master/onnx2keras/layers.py#L18

Some of the missing converters are: Equal, Where...

Thank you

**Comment by jegou** [comment]
Dear @LamyaMohaned 

This sounds like more a question for the authors of onnx2keras than for us. We are not supporting Keras or onnx2keras.

Best
