### ISSUE TITLE
Real accuracy does not match reported accuracy during training

### ISSUE THREAD

**Issue by olivierlam97** [facebookresearch/deit#130]
Hello!

First, thank you for your very interesting work!

I have an issue when training the 'deit_base_patch16_384' model on a custom dataset with 235 classes.
I formatted my data to match the IMNET format as below (the name of each folder is the category_id) and I got approximatively 60% accuracy for the test set (from the output of the training)

`/path/to/imagenet/ 
  train/
    0/
      img1.jpeg
    1/
      img2.jpeg
  val/
    0/
      img3.jpeg
    1/
      img4.jpeg
`

However, when using the model, the predictions were completely incorrect. I manually predicted the category_id for each images and compared with the groundtruth category_id, and got only 27 correct predictions over more than 7000 test images.

My question is the following: should the prediction of the category_id match the category_id from the folder name ?

Thank you in advance!

Olivier

**Comment by TouvronHugo** [comment]
Hi @olivierlam97 ,
You can check the order of the classes this way:
`
train_set = datasets.ImageFolder('/path/to/custom_dataset/')
train_set.classes
`
Best,
Hugo

**Comment by TouvronHugo** [comment]
Hi @olivierlam97 ,
You can for example convert the targets before using them in the loss to get the order you want.
Best,
Hugo
