### ISSUE TITLE
Fine-tune on pre-trained models

### ISSUE THREAD

**Issue by Xin-hhh** [facebookresearch/deit#133]
How to use the fine-tune code given in the paper for transfer learning, e.g. for a binary classification task. Thank you very much.

**Comment by TouvronHugo** [comment]
Hi @Xin-hhh,
Thanks for your question.
You have to add the new dataset in the code and adapt the number of classes. Then I think you should also adapt some training hyper-parameters for the new dataset.
Best,
Hugo
