### ISSUE TITLE
Kl divergence in distillation loss

### ISSUE THREAD

**Issue by Blosslzy** [facebookresearch/deit#134]
Hi! Thank you for your excellent work and sharing spirit!
I want to use DeiT in the deepfake video detection task with small dataset. So I use the pretrained Deit-B as student and Xception as teacher, Xception is pretrained in this deepfake face dataset. But I got very small result of F.KL_div() in the first epoch, about 4e-5. I wonder if this number is normal.
Looking forward to your replay!

**Comment by TouvronHugo** [comment]
Hi @Blosslzy,
Thanks for your question, 
Indeed, this seems quite low. Maybe you can try hard distillation in order to see if it works better.
Best,
Hugo

**Comment by Ga-Lee** [comment]
> Hi @Blosslzy, Thanks for your question, Indeed, this seems quite low. Maybe you can try hard distillation in order to see if it works better. Best, Hugo

Hello! I want to know when using hard distillation,what is the coefficient  value **self.alpha**  for distillation_loss, does it equal to the default value 0.5? 
Thank you for your reply!
