### ISSUE TITLE
Architecture definition and pretrained models of PatchConvNet

### ISSUE THREAD

**Issue by beiluo97** [facebookresearch/deit#135]
Hello!
I'm glad to see amazing sate-of-the-art work [PatchConvNet](https://arxiv.org/abs/2112.13692), and I read the article and learned a lot out of it.The paper mentions that "We share the architecture definition and pretrained models," but I could not find the code for PatchConvNet.
Could you please point me in the right direction?
Thanks!

**Comment by TouvronHugo** [comment]
Hi @beiluo97,
Thanks for your question. 
We will publish the code soon, I'll keep you informed.
Best,
Hugo

**Comment by TouvronHugo** [comment]
I have just uploaded the models

**Comment by beiluo97** [comment]
> I have just uploaded the models

Thanks for you so much!
