### ISSUE TITLE
Request for training logs

### ISSUE THREAD

**Issue by HeegonJin** [facebookresearch/deit#137]
Hi, 

I've checked other issues to find training logs and I was able to get training log of 'deit_small_distilled_patch16_224' model
thanks to (https://github.com/facebookresearch/deit/issues/18).

Could you also share the training logs of other distilled versions like 'deit_tiny_distilled_patch16_224' and 'deit_base_distilled_patch16_224' and 'deit_base_distilled_patch16_384'?

**Comment by TouvronHugo** [comment]
Hi @HeegonJin ,
Thanks for your question.
We have no plans to share additional training logs in the near future. I will keep you informed.
There are more logs [here](https://github.com/facebookresearch/deit/issues/96#issuecomment-848647660).
Best,
Hugo
