### ISSUE TITLE
`kxd` matrix or `1xd` vector?

### ISSUE THREAD

**Issue by densechen** [facebookresearch/deit#139]
In section 3 of paper 'Augmenting Convolutional networks with attention-based aggregation':
···
We can easily specialize the attention maps per class by replacing the CLS vector with a k × d matrix, where each of the k columns is associated with one of the classes. This specialization allows us to visualize an attention map for each class, as shown in Figure 2.
···
But I only found `1 x d` vector. Where is `k x d` matrix?

https://github.com/facebookresearch/deit/blob/40ae72b79cc5cd48dac2b02e1fceb03ee4192676/patchconvnet_models.py#L201

**Comment by jegou** [comment]
Dear @densechen, 

as stated in the paper (see discussion in Section 3.2),  
"By default, we use the more convenient single class token."

The code that we provide for now corresponds the main model based on the vector, which corresponds to most of our results (in Table 2 we provide the result of S60 when specializing the attention per class).

**Comment by jegou** [comment]
We will provide the S60 model and weights used to generate the visualization in our paper.  

cc @TouvronHugo

**Comment by densechen** [comment]
It seems ridiculous. 
![image](https://user-images.githubusercontent.com/14089191/147841596-740b33e7-ef23-4f1c-bce4-313caf7b931d.png)

`one class-token per class` works worse then `a single class-token` in Table 5. 
Actually, `one class-token per classes` is not used in the released code or the experiments described in the paper.

Why spend so much time describing a design that doesn't work? Or just for a better visualization?

At the first glance, we think this `one class-token per class` is a key design which is quite different from the one in ViT.

**Comment by jegou** [comment]
This design is introduced as a straightforward variation of our learned aggregation layer. And yes: mostly for vizualization. 

In Figure 1 most of our result are with 1 token. I am sorry if you think you find we have spend 'much time', I actually thought that we were presenting it as a straightforward variation of our main proposal: only the sentence 'We can specialize this attention per class' in Figure 1 for the last column, and a small paragraph in Section 3, where we point out some limitations of this variant. Maybe the confusing part is Fig. 3, where we could easily explain the tiny difference between both choices. 

So yes, our paper has a significant focus on how to provide vizualisation and some interpretable aggregation layer to convnets, this is also true for the single-token version. 
 
The choice of the single token is driven by a more direct relationship to this objective, as it provides the weight of each patch in the aggregation. The one-class-token provides a weight per patch for each class, independent of whether the class is selected or not by the classifier. While both have their pros and cons, we feel like they are complementary for vizualisation purposes. 

Hervé

**Comment by TouvronHugo** [comment]
Hi @densechen,

I have added the code and the model S60 for the multi-class token version. As discussed in the paper, this model is difficult to learn from scratch compared to the model with 1 class token, which explains the performance of 81.1% reported in Table 5. 

This is why, in our paper (see page 3 and text-image below), we recommend to fine-tune the multi-class token model from the weights of the single-class token model. In that case the model is easier to train, you typically get comparable results to the single token-case. For instance for the S60 we obtain 82.0% for multi-token vs 82.1% for the single-token architecture. 

I will add the weights next week. I hope this addresses your concern. 

Best,
Hugo

----------
![271043633_220258640193496_302056670822730861_n](https://user-images.githubusercontent.com/49280617/148565587-f04000f1-749f-4cd0-a48f-e8aba8281e1e.png)

**Comment by densechen** [comment]
@TouvronHugo Thanks for your kindly reply. Your detailed explanation makes me know better about the whole process. Thanks!
