### ISSUE TITLE
Question about attention based pooling

### ISSUE THREAD

**Issue by ZihaoH** [facebookresearch/deit#142]
Thanks for the great work!
After I seeing the code, it seems that the attention based pooling is one layer of transformer where query is only the class token. Am I understand right, or something I missed? The part of attention based pooling of Fig. 3 in your paper is a little bit confusion for me. Hard to see the input for the 3 Linear layer.

**Comment by TouvronHugo** [comment]
Hi @ZihaoH,
Thanks for your question.

The attention based pooling with a single class token can be seen like this.  Nevertheless, there are some others simplifications like using a single head.

In Fig 3 we represent the attention based pooling with multi-class tokens. So for ImageNet in q there is the 1000 class tokens (1 class token for each class) and in k and v there is only the patches of the image.
In Fig 3 (top to bottom):
- the  first linear represent the projection for q the inputs are the class token giraffe, dog, zebra
- the  second linear represent the projection for k the inputs are the image patches
- the  third linear represent the projection for v the inputs are the image patches

Best,
Hugo
