### ISSUE TITLE
RuntimeError: Cannot find callable

### ISSUE THREAD

**Issue by ahmedeqbal** [facebookresearch/deit#143]
Hello,

currently, i am using:

Torch 1.10.1
Torchvision 0.11.2
Tmm 0.4.12

i am facing following error, please help

```
  File "C:\Users\Ahmed\Desktop\Ahmed\Code\PyTorch\models\net.py", line 97, in __init__
    transformer = torch.hub.load('facebookresearch/deit:main', 'deit_tiny_distilled_patch16_224', pretrained=True)
  File "C:\Users\Ahmed\miniconda3\envs\torch\lib\site-packages\torch\hub.py", line 399, in load
    model = _load_local(repo_or_dir, model, *args, **kwargs)
  File "C:\Users\Ahmed\miniconda3\envs\torch\lib\site-packages\torch\hub.py", line 427, in _load_local
    entry = _load_entry_from_hubconf(hub_module, model)
  File "C:\Users\Ahmed\miniconda3\envs\torch\lib\site-packages\torch\hub.py", line 235, in _load_entry_from_hubconf
    raise RuntimeError('Cannot find callable {} in hubconf'.format(model))
RuntimeError: Cannot find callable deit_tiny_distilled_patch16_224 in hubconf
```

**Comment by TouvronHugo** [comment]
Hi @ahmedeqbal,
This error seems not related to the deit repo I just tested this in a colab notebook (timm 0.4.12,torch 1.10.0, torchvision 0.11.1 ) and it works.
Maybe there is a problem with your conda environment.
![colab](https://user-images.githubusercontent.com/49280617/150134240-4d9e0f09-2702-4c5f-9a8b-952c9757d52c.png)
Best,
Hugo

**Comment by ahmedeqbal** [comment]
Please check attached screenshot, Yes, in Python environment it works, but when i call by "Python train.py" file, it shows the bottom following error.

![image](https://user-images.githubusercontent.com/7148894/150136471-96e21017-d5a2-44f0-b4a9-e98a69dd56af.png)

**Comment by TouvronHugo** [comment]
I just tested by putting the code in a .py file and running it with python and it works.
I think the problem comes from your code or from your conda environment.
Best,
Hugo

**Comment by ahmedeqbal** [comment]
> I just tested by putting the code in a .py file and running it with python and it works. I think the problem comes from your code or from your conda environment. Best, Hugo

Hello,

if you have run code at your local machine via **.py** file, please share current version of  your installed **Conda, Python, Torch, Torchvision, and Tmm** ? maybe, this requirement will help me to resolve this issue.

**Comment by TouvronHugo** [comment]
Yes sure,
It works with my 2 configs:

config 1:
- python 3.9.6
- torchvision 0.9.1
- timm 0.4.12
- pytorch 1.8.1
- conda 4.10.1

config 2:
- python 3.9.7
- torchvision 0.11.1
- timm 0.4.12
- pytorch 1.10.0
- conda 4.10.1
