### ISSUE TITLE
Adjusting min-lr in cosine schedule to batch and world size

### ISSUE THREAD

**Issue by nasimrahaman** [facebookresearch/deit#144]
The peak learning rate [is scaled](https://github.com/facebookresearch/deit/blob/main/main.py#L304) according to `lr = base_lr * batch_size * world_size / 512`, but this adjustment does not appear to be made for the min learning rate of the cosine schedule, which seems to be [fixed](https://github.com/facebookresearch/deit/blob/main/main.py#L75) at 1e-5. 

This implies that using a smaller batch size will shrink the range over which the learning rate decays. Is this intended behaviour?

**Comment by TouvronHugo** [comment]
Hi @nasimrahaman,
Yes you are absolutely right but the scaling of min lr should not follow the same rule as the peak Learning rate. We did not study how to scale it well so we left it like that by default.
Best,
Hugo
