### ISSUE TITLE
Why should we set different seed per gpu with DDP?

### ISSUE THREAD

**Issue by developer0hye** [facebookresearch/deit#150]
https://github.com/facebookresearch/deit/blob/35cd4556c06929c59247b828d7dd778b44328fd4/main.py#L182

Hi!

I recently referenced this project to implement DDP training code, and I can successfully implement and reproduce the performance of [our model](https://github.com/MarkAny-Vision-AI/CenterNeXt), thanks to this project.

I have one question related to DDP.

Why should we set different seed per gpu with DDP?

**Comment by TouvronHugo** [comment]
Hi @developer0hye,
Thanks for your question,
It is to be sure that the operations where we can be led to draw random values as for instance for data-augmentations will not be exactly the same between the different GPUs.
Best,
Hugo

**Comment by developer0hye** [comment]
@TouvronHugo 
Hi @TouvronHugo 
I got it! Thanks!
