### ISSUE TITLE
why does the distilled model outperform its teacher?

### ISSUE THREAD

**Issue by HIT-LiuChen** [facebookresearch/deit#153]
Thanks for your exciting work and open-soure code.I noted that "Interestingly, the distilled model outperforms its teacher in terms of the trade-off between accuracy and throughput. " is declared in paper. In usually, the distilled model can't learn generalization ability from teacher model totally. I wonder that the gain on accuracy is from truth label or other tricks. Would you mind analysing the reason briefly? Thanks a lot.

**Comment by TouvronHugo** [comment]
Hi @HIT-LiuChen,
Thanks for your question.
The teacher will correct the errors of the ground truth labels during the training.
These errors may be related to data-augmentation or annotation errors.
For example, with RandomResizedCrop the crop of the image may no longer contain the main object of the image.
I hope I've answered your question, let me know if you need any clarification.
Best,
Hugo

**Comment by HIT-LiuChen** [comment]
Thanks for your replying a lot! 
In fact, the Transformer model can learn knowledge well from truth labels, and the teacher corrects the errors during the training. Both of them lead the excellent gain on accuracy which is even better than teacher model. Is my perceptino right?

**Comment by HIT-LiuChen** [comment]
Thanks again. Have a good day!

**Comment by TouvronHugo** [comment]
Thanks, good day to you too!
