### ISSUE TITLE
About the weight decay settings in ResMLP models

### ISSUE THREAD

**Issue by rentainhe** [facebookresearch/deit#158]
Refer to this comment https://github.com/facebookresearch/deit/issues/106#issuecomment-896541441

There is no weight decay on `layer_scale` and `Affine Layer`, I have no idea where did you set the weight-decay param on theses layers~, would you like to provide the training command line for ResMLP models~

**Comment by TouvronHugo** [comment]
Hi @rentainhe,
The weight decay is set in [create_optimizer](https://github.com/facebookresearch/deit/blob/a2ffd162edc49b30f6ed8044cd10444bf2ae1299/main.py#L342).
You don't need to specify this in the command line to train ResMLP models.
Best,
Hugo
