### ISSUE TITLE
DeiT III code release

### ISSUE THREAD

**Issue by bhheo** [facebookresearch/deit#159]
Hi

I recently read an extended study of deit "DeiT III: Revenge of the ViT".
I was impressed with this work. I think it might greatly contribute to research on ViT.
I want to apply DeiT III setting to my research.

Do you have any plans to release code for DeiT III ?
I think I can try to reproduce it but the official code is always better than the reproduced one.
So, I'd like to know if the code will be released in the near future or not.

**Comment by TouvronHugo** [comment]
Hi @bhheo,
Thanks for your message.
Yes of course I think the code should be online as well as the weights of the different models the first week of May.
I'll keep you informed.
Best,
Hugo

**Comment by bhheo** [comment]
Thank you for your reply.
I will be waiting for your code.

Regards
Byeongho Heo

**Comment by TouvronHugo** [comment]
Hi @bhheo ,
We have just released code and models.
Best,
Hugo
