### ISSUE TITLE
--nb_classes for ImageNet-21k pretraining

### ISSUE THREAD

**Issue by tgxs002** [facebookresearch/deit#161]
Hi Hugo,

I noticed that the suggested command for pretraining DeiT III on IN-21k set --nb_classes to 1000, which is smaller than the number of classes of IN-21k. 

Is it a typo?

Best,
Blakey

**Comment by tgxs002** [comment]
Oh, it is modified in the code... The command line parameter does not matter...

**Comment by mxjecho** [comment]
hi @tgxs002 , could you please tell me where is the code for modifying the nb_classes of 21K?
