### ISSUE TITLE
Finetune setting for DeiT-III at IN1k

### ISSUE THREAD

**Issue by bhheo** [facebookresearch/deit#162]
Hi

Thank you for sharing valuable codes.
I'm trying to reproduce your results with A100 GPUs

For pretraining, I got a very similar result to paper or #160 on IN-1k with ViT-S, B.
But, I'm not sure which setting I have to use for ViT-B fine-tuning on 224 resolution.
Could you please share 224 resolution finetune code for ViT-B pretrained on ImageNet-1k 192 resolution?
If the code is already included and I missed it, please let me know.

**Comment by Dongshengjiang** [comment]
+1

**Comment by TouvronHugo** [comment]
Hi @bhheo and @Dongshengjiang ,

Thanks for your message,

I will add this to the README by tomorrow.
I'll keep you posted.
Best,
Hugo

(Sorry for the late reply I just come back from PTO ;) )

**Comment by TouvronHugo** [comment]
It's done
