### ISSUE TITLE
I want to know when is the distillation token used?

### ISSUE THREAD

**Issue by HC-super** [facebookresearch/deit#163]
When to use convnet as a teacher and distillation token as a method to distillate the model? During the pre-training or fine-tune the student model? And how to initialize the DeiT model (use ViT's weights?)?

**Comment by TouvronHugo** [comment]
Hi @HC-super,
Thanks for your message.

It is possible to use distillation during pre-training and fine-tuning to get better results. However, using it only during the pre-training gives already very good results.
For the initialization of the models before the pre-training it is random and for the fine tuning we initialize with the pre-trained model.

I hope this answers your questions.
Best,
Hugo
