### ISSUE TITLE
Question about the hard-label distillation and mixup

### ISSUE THREAD

**Issue by zysong0113** [facebookresearch/deit#168]
Hi! Thank you for your excellent work and sharing spirit!
I have a little problem about the hard-label distillation and the mixup data augmentation. In the hard-label distillation you proposed, the teacher prediction plays the same role as the true label, which is also implemented in the code with argmax. I wonder if mixup data augmentation can still be used in this case? Since the images fed into the teacher and the students are same, but mixup will change the true labels. Will the hard-label distillation conflict with the mixup augmentation?

Looking forward to your replay!

**Comment by TouvronHugo** [comment]
Hi @zysong0113,
Thanks for your question.
Very good question, indeed can be used with hard distillation. Mixup changes the true labels but also the prediction of the teacher. So there is no conflict between hard-label distillation  and Mixup.
Best,
Hugo
