### ISSUE TITLE
How to reproduce DeitIII for semantic segmentaion

### ISSUE THREAD

**Issue by jianlong-yuan** [facebookresearch/deit#170]
I have tried to reproduce DeitIII for semantic segmentation, but i just got a few lower than the paper 53.4(VIT-B). Could you release config for semantic segmentation?

**Comment by jianlong-yuan** [comment]
any news?

**Comment by TouvronHugo** [comment]
Hi @jianlong-yuan,
Thanks for your question.
In the paper we used our baseline train from scratch at resolution 224x224 on ImageNet; we have not yet released these models so you need to pre-train them if you want to reproduce our semantic segmentation results.
For the semantic segmentation configuration our code is based on the XCiT paper.
I will add the 224x224 models and the semantic segmentation config to facilitate the reproducibility but not in the near future (Maybe in September).
Best,
Hugo
