### ISSUE TITLE
Can someone explain the comment on this line?

### ISSUE THREAD

**Issue by HashmatShadab** [facebookresearch/deit#177]
https://github.com/facebookresearch/deit/blob/8ab59156f435cc7be62791ed2edbc65553fc665f/main.py#L423

**Comment by TouvronHugo** [comment]
Hi @HashmatShadab,
Thanks for your question,
In order to reproduce the results you should have `train_mode=True` except to reproduce the deit finetuning results.
Best,
Hugo

**Comment by HashmatShadab** [comment]
So for deit finetuning , if we set the mode to eval, what parameters are we updating then?

**Comment by TouvronHugo** [comment]
All the parameters eval mode does not affect the update of the model weights

**Comment by TouvronHugo** [comment]
Yes, that's right

**Comment by HashmatShadab** [comment]
Thanks!
