### ISSUE TITLE
ImageNet21k pretrained model without finetuning on 1k

### ISSUE THREAD

**Issue by bhheo** [facebookresearch/deit#181]
Hi

I'm trying to reproduce DeiT-III's ImageNet-21k results
Could you please share ViT-B weight which is pretrained on 21k but not fine-tuned on 1k?
It will be a great help to check and validate my pretraining

Best
Byeongho Heo

**Comment by TouvronHugo** [comment]
Hi @bhheo,
Thanks for your message.
I'll try to share the weight soon.

Best,

Hugo

**Comment by lucasb-eyer** [comment]
Hey, I was also looking for this recently, and found the title in the README to be pretty ambiguous, so only understood they are the fine-tuned ones after loading and looking at shapes.
