### ISSUE TITLE
Is uniform drop-path rates beneficial ?

### ISSUE THREAD

**Issue by bhheo** [facebookresearch/deit#184]
Hi

Thank you for your work and kind replies. It is a great help for my research

I just found that DeiT-III uses uniform drop-path rates.
https://github.com/facebookresearch/deit/blob/8ab59156f435cc7be62791ed2edbc65553fc665f/models_v2.py#L200

This implementation is different from timm or DeiT's drop-path rate.
```python
dpr = [x.item() for x in torch.linspace(0, drop_path_rate, depth)]  # stochastic depth decay rule
```
https://github.com/rwightman/pytorch-image-models/blob/c45c6ee8e406861898acccb1818f91d0c9240e48/timm/models/vision_transformer.py#L376

I never tried this drop-path setting. So, I want to ask your opinion or experience on it.
Is this uniform drop-path rate beneficial for performance?

**Comment by TouvronHugo** [comment]
Hi @bhheo,
Thanks for your question.
There is not much difference in terms of performance. We use a uniform drop path with architectures that do not have pooling because it is conceptually simpler.
Best,
Hugo

**Comment by bhheo** [comment]
It is not for the performance.
Thank you for your answer.
It looks simple and cool.

Best
Byeongho Heo
