### ISSUE TITLE
Object detection from the DeiT III pretrained model

### ISSUE THREAD

**Issue by YuanLiuuuuuu** [facebookresearch/deit#187]
After I replace the commonly used random resized crop with the simple resized crop from DeiT III, I find the performance on object detection degrades sharply. But image classification and semantic segmentation are unaffected. Have you ever run object detection, initialized by the supervised pre-trained weights of DeiT III. If so, did you observe the same degradation of performance on object detection task?  I will be grateful if you can explain this phenomenon. Thanks!

**Comment by YuanLiuuuuuu** [comment]
@TouvronHugo

**Comment by TouvronHugo** [comment]
Hi @YuanLiuuuuuu,
Thanks for your message. 
No we have not tested this. That's a pretty interesting observation. You have experimented this with models that you have pre-trained on which dataset?
Best,
Hugo
