### ISSUE TITLE
Question about Throughput

### ISSUE THREAD

**Issue by techmonsterwang** [facebookresearch/deit#189]
Hi, very nice work!

But I wonder how to measure the Throughput results? (such as DeiT-Ti for 2536.5 images/s) where is the code for this function?

Thanks a lot!

**Comment by TouvronHugo** [comment]
Hi @techmonsterwang,
Thanks for your message, the code is [here](https://gist.github.com/fmassa/1f4edb34ca041634c9b730473753b8ad).
Best,
Hugo
