### ISSUE TITLE
cifar100 pretrain model?

### ISSUE THREAD

**Issue by Wang-Y-S** [facebookresearch/deit#191]
Hi:

Your research is amazing,
i spend a lot of time to know this fantastic article,
and, i have some idea want to try for small scale dataset,
Did you have all the cifar100 pretrained model?
or how can I get pretrained model,
Can you give me some tips?

Best regard!
Thank you so much!!
Wang-Y-S

**Comment by TouvronHugo** [comment]
Hi @Wang-Y-S,
Thanks for your message.
Unfortunately, I don't have a model train on CIFAR-100 from scratch currently available.
If you want to train one you can use the Deit training config on ImageNet but maybe it's better not use erasing, train for 1000 epochs with a convent teacher trained on CIFAR-100.
Best,
Hugo
