### ISSUE TITLE
Removing Last FC layer & manual looping

### ISSUE THREAD

**Issue by jaideepmurkute** [facebookresearch/deit#2]
I need to insert custom layers between the transformer modules and classify among K(!=1000) classes. 
For that, If I try to remove last FC layer and loop over other modules manually, it yields the output of size (batch_size, 196, 768) instead of expected (batch_size, 768): 

**Removing last layer:** 
```
self.model = torch.hub.load('facebookresearch/deit:main', 'deit_base_patch16_224', pretrained=True)
self.model = nn.Sequential(*list(self.model.children())[:-1])
```

**Manual looping:**
input: (batch_size, 3, 224, 224)
```
output = self.model[1](self.model[0](input))    # (patch_embed & pos_drop;   output_size: (batch_size, 196, 768))
for i in range(0, 12):  
    output = self.model[2][i](output)     # transformer blocks;   output_size: (batch_size, 196, 768)
output = self.model[3](output)    # LayerNorm;   output_size: (batch_size, 196, 768)
```

Doing self.model(input) works as expected. (i.e. no manual looping).
Am I doing something wrong? This usually works for other torchvision models.

**Comment by TouvronHugo** [comment]
Hi @jaideepmurkute,
I think it works with torchvision models because they should be sequential models. 
To be able to make the changes you need, I think you'll have to rewrite the forward of the model.
I hope I have answered your question, don't hesitate if you have any other questions.
Best,
Hugo

**Comment by fmassa** [comment]
Hi,

As @TouvronHugo mentioned, the implementation for removing the last layer of the model as you have specified only works in a small subset of the PyTorch models.

DeiT models are based on `timm` [`VisionTransformer`](https://github.com/rwightman/pytorch-image-models/blob/392595c7eb02c3f6353a7806aa9d1e3f569d47e7/timm/models/vision_transformer.py#L204). If you want to remove the classifier output and add your own custom layers, you can see how the [`forward`  of the model](https://github.com/rwightman/pytorch-image-models/blob/392595c7eb02c3f6353a7806aa9d1e3f569d47e7/timm/models/vision_transformer.py#L280-L283) is implemented.

In this case, I would recommend you doing something like the following:
```python
output = self.model.forward_features(input)
```

I believe I've answered your question and as such I'm closing this issue, but let us know if you have further questions.
