### ISSUE TITLE
Does the EMA is used in DeiT-III?

### ISSUE THREAD

**Issue by mzr1996** [facebookresearch/deit#203]
I'm working on reproducing the accuracy of DeiT-III, and I notice that the EMA is enabled during pre-training, but it's not used during evaluation. So does the EMA model is used in any location?

**Comment by netw0rkf10w** [comment]
In my experience, model EMA is not helpful for ViT in general, so DeiT-III probably did not use it, but of course we should wait for a confirmation from @TouvronHugo.

**Comment by TouvronHugo** [comment]
Hi @netw0rkf10w and @mzr1996,
Yes, we did not use EMA because it's not helpful with our training recipes.
Best regards,
Hugo

**Comment by mzr1996** [comment]
Thanks
