### ISSUE TITLE
Can I use timm==0.4.12 instead of timm==0.3.2 ?

### ISSUE THREAD

**Issue by irhallac** [facebookresearch/deit#206]
I have created an conda env and installed the following:
`conda install -c pytorch pytorch torchvision`
`pip install timm==0.3.2`

I tried to run the main.py for evaluation. Gives the following error:
`With the given cannot import name 'container_abcs' from 'torch._six'`
Is there a fix for this package issue?

Alternatively I tried to evaluate (DeiT-base) with timm==0.4.12
I got the Acc@1 81.802  instead of 81.846. Is this slight difference caused by the difference of timm versions ?

**Comment by xijiu9** [comment]
I think that the random seed can cause some change in the accuracy, so it does not matter.
