### ISSUE TITLE
Meaning of the model name ( ResMLP)

### ISSUE THREAD

**Issue by YHYeooooong** [facebookresearch/deit#207]
Hello, thanks for sharing great work!

I had small question of the model name.
I wondering about the meaning of 'S24' in ResMLP-S24. I think 'S' can mean a small-scale model and '24' may mean that model was consist of 24 layers. But I can not find any description in the paper. 

Could you tell me the meaning like 'S24' or 'B24' ?
Thanks!

**Comment by TouvronHugo** [comment]
Hi @YHYeooooong ,
Yes S mean working dim 384, B working dim 768 and 24 the number of layers.
Best regards,
Hugo
