### ISSUE TITLE
Can you provide the CUDA version and the hardwares training DeiT on ImageNet?

### ISSUE THREAD

**Issue by Yuxin-CV** [facebookresearch/deit#21]

**Comment by Yuxin-CV** [comment]
Hello, thanks for your wonderful work!
The training time report in the DeiT paper is too ambiguous, and I wonder what CUDA version and the hardwares you use to train DeiT.
I think the training time is very closely related to the CUDA version as well as the hardwares, so I think it is necessary to report  
this information in conjunction with the training time.

**Comment by ZhiyuanChen** [comment]
Around 0.9s/step on V100 with CUDA 11

**Comment by Yuxin-CV** [comment]
> Around 0.9s/step on V100 with CUDA 11

Hello! 
For me, around 5min22s ± 1s / epoch on 8x 2080ti w/ CUDA 10.0, batchsize_per_GPU = 256, raw image on the Hadoop.

**Comment by fmassa** [comment]
Hi,

We trained our models using PyTorch 1.7.0 with CUDA 10.1, running on V100 GPUs with 32GB of memory.

I believe I've answered your question and as such I'm closing this issue but let us know if you have any further questions.
