### ISSUE TITLE
how to implement document layout analysis use Deit-B

### ISSUE THREAD

**Issue by sherryhsy** [facebookresearch/deit#210]
I try to use Deit-B to implement document layout analysis, but there is no corresponding code and training scheme

**Comment by TouvronHugo** [comment]
Hi @sherryhsy ,
Unfortunately we have no code for this specific task.
Best,
Hugo

**Comment by mllife** [comment]
@sherryhsy, any update on this, it seems LayoutLMv3 and DiT are only for research exploration.
