### ISSUE TITLE
Acc-FLOPs trade-off of DeiT and comparison with other models

### ISSUE THREAD

**Issue by Yuxin-CV** [facebookresearch/deit#22]
Hi, thanks for your wonderful work!
I wonder the Acc-FLOPs trade-off of DeiT. Will you consider provide this data in the future?

**Comment by TouvronHugo** [comment]
Hi @Yuxin-CV,
We have not yet calculated the Acc-FLOPs trade-off of DeiT.
For the moment we don't plan to do it but this may change.
Best,
Hugo
