### ISSUE TITLE
Single image inference

### ISSUE THREAD

**Issue by pablobots** [facebookresearch/deit#3]
Hi, what is the best way to make a single image inference on a pre-trained model?

**Comment by zhiqwang** [comment]
It seems that other scripts that can be infer torchvision's model can also be used here, for example:

```python
from PIL import Image
import torch
import timm

import torchvision.transforms as transforms

from timm.data.constants import IMAGENET_DEFAULT_MEAN, IMAGENET_DEFAULT_STD

# now load it with torchhub
model = torch.hub.load('facebookresearch/deit:main', 'deit_base_patch16_224', pretrained=True)

model.eval()

transform = transforms.Compose([
    transforms.Resize(256, interpolation=3),  # to maintain same ratio w.r.t. 224 images
    transforms.CenterCrop(224),
    transforms.ToTensor(),
    transforms.Normalize(IMAGENET_DEFAULT_MEAN, IMAGENET_DEFAULT_STD),
])

img_path = './data-bin/demo/cat.jpg'
img = Image.open(img_path).convert("RGB")
img = transform(img)[None,]

out = model(img)
pred_label = torch.argmax(out)
```

**Comment by pablobots** [comment]
> 
> 
> It seems that other scripts that can infer torchvision's model can also be used here, for example:
> 
> ```python
> from PIL import Image
> import torch
> import timm
> 
> import torchvision.transforms as transforms
> 
> from timm.data.constants import IMAGENET_DEFAULT_MEAN, IMAGENET_DEFAULT_STD
> 
> # now load it with torchhub
> model = torch.hub.load('facebookresearch/deit:main', 'deit_base_patch16_224', pretrained=True)
> 
> model.eval()
> 
> transform = transforms.Compose([
>     transforms.Resize(256, interpolation=3),  # to maintain same ratio w.r.t. 224 images
>     transforms.CenterCrop(224),
>     transforms.ToTensor(),
>     transforms.Normalize(IMAGENET_DEFAULT_MEAN, IMAGENET_DEFAULT_STD),
> ])
> 
> img_path = './data-bin/demo/cat.jpg'
> img = Image.open(img_path).convert("RGB")
> img = transform(img)[None,]
> 
> out = model(img)
> pred_label = torch.argmax(out)
> ```

Great, but how I would load a checkpoint.pth file?

**Comment by zhiqwang** [comment]
If your classes number is equal to 1000, one way to load a custom checkpoints as following:

```python
model = torch.hub.load('facebookresearch/deit:main', 'deit_base_patch16_224', pretrained=False)
ckpt_path = '~/.cache/torch/hub/checkpoints/deit_base_patch16_224-b5f2ef4d.pth'

ckpt_dict = torch.load(ckpt_path)
model.load_state_dict(ckpt_dict["model"])
model.eval()
```
