### ISSUE TITLE
ValueError: LocalExecutor can use only one node. Use nodes=1

### ISSUE THREAD

**Issue by pawopawo** [facebookresearch/deit#31]
Traceback (most recent call last):
  File "run_with_submitit.py", line 131, in <module>
    main()
  File "run_with_submitit.py", line 116, in main
    **kwargs
  File "/opt/tiger/conda/lib/python3.7/site-packages/submitit/core/core.py", line 638, in update_parameters
    self._internal_update_parameters(**kwargs)
  File "/opt/tiger/conda/lib/python3.7/site-packages/submitit/auto/auto.py", line 197, in _internal_update_parameters
    self._executor._internal_update_parameters(**parameters)
  File "/opt/tiger/conda/lib/python3.7/site-packages/submitit/local/local.py", line 158, in _internal_update_parameters
    raise ValueError("LocalExecutor can use only one node. Use nodes=1")
ValueError: LocalExecutor can use only one node. Use nodes=1

**Comment by fmassa** [comment]
Hi,

By default, `run_with_submitit` (which dispatches to `submitit`) will use the `AutoExecutor` to run your code. It tried to locate slurm in your machine (to schedule jobs in a cluster), without success, so it defaulted to the `LocalExecutor`, which runs the job in the same machine.

This means that you can't use more than a single node (= machine) for training. The default command we have for `run_with_submitit` assumes 2 nodes, so you should change to passing `--nodes 1` instead.

Alternatively, if you are not running with multiple machines, you can skip using `run_with_submitit.py` and run directly from `main.py`:
```
python -m torch.distributed.launch --nproc_per_node=8 --use_env main.py
```

I believe I've answered your question, and as such I'm closing this issue, but let us know if you have any further questions

**Comment by dal-code** [comment]
> 
As you said，it is a machine problem？

**Comment by dal-code** [comment]
> 
As you said，it is a machine problem？


> Hi,
> 
> By default, `run_with_submitit` (which dispatches to `submitit`) will use the `AutoExecutor` to run your code. It tried to locate slurm in your machine (to schedule jobs in a cluster), without success, so it defaulted to the `LocalExecutor`, which runs the job in the same machine.
> 
> This means that you can't use more than a single node (= machine) for training. The default command we have for `run_with_submitit` assumes 2 nodes, so you should change to passing `--nodes 1` instead.
> 
> Alternatively, if you are not running with multiple machines, you can skip using `run_with_submitit.py` and run directly from `main.py`:
> 
> ```
> python -m torch.distributed.launch --nproc_per_node=8 --use_env main.py
> ```
> 
> I believe I've answered your question, and as such I'm closing this issue, but let us know if you have any further questions

**Comment by dal-code** [comment]
> Hi,
> 
> By default, `run_with_submitit` (which dispatches to `submitit`) will use the `AutoExecutor` to run your code. It tried to locate slurm in your machine (to schedule jobs in a cluster), without success, so it defaulted to the `LocalExecutor`, which runs the job in the same machine.
> 
> This means that you can't use more than a single node (= machine) for training. The default command we have for `run_with_submitit` assumes 2 nodes, so you should change to passing `--nodes 1` instead.
> 
> Alternatively, if you are not running with multiple machines, you can skip using `run_with_submitit.py` and run directly from `main.py`:
> 
> ```
> python -m torch.distributed.launch --nproc_per_node=8 --use_env main.py
> ```
> 
> I believe I've answered your question, and as such I'm closing this issue, but let us know if you have any further questions

Many thanks for your replying！ As you said，‘’LocalExecutor can use only one node Use nodes=1‘’ is a machine problem？
