### ISSUE TITLE
Code for distillation part

### ISSUE THREAD

**Issue by ZhangChao1993** [facebookresearch/deit#35]
Could share us code for distillation part？ Your paper【Training data-efficient image transformers
& distillation through attention】is great，and I find 【data-efficient】part in your code, but without distillation part.

**Comment by fmassa** [comment]
Hi,

We are working on preparing the release for the distillation part in https://github.com/fmassa/deit/tree/distillation, and we will be opening a PR once we finish validating that the refactored code works, which should be later this week.

**Comment by ZhangChao1993** [comment]
> Hi,
> 
> We are working on preparing the release for the distillation part in https://github.com/fmassa/deit/tree/distillation, and we will be opening a PR once we finish validating that the refactored code works, which should be later this week.

Thanks for your great work! By the way,  can you share us fine-tuing code? I tried 384 for pretrained model and cannot work! 
 Others need this too!
[https://github.com/facebookresearch/deit/issues/41]

**Comment by fmassa** [comment]
Hi,

Code for distillation has been merged into master, and the code for finetuning is in https://github.com/facebookresearch/deit/pull/43 and will be merged soon. Once they are merged I'll upload the weights for the pre-trained models.

**Comment by fmassa** [comment]
Hi,

We've merged the code for distillation and finetuning in #42 and #43, and added the pre-trained weights in #50.
Given that those are now available, I'm closing this issue but let us know if you have any further questions
