### ISSUE TITLE
multi node training

### ISSUE THREAD

**Issue by pawopawo** [facebookresearch/deit#37]
Hi, the code will always stay [here](https://github.com/facebookresearch/deit/blob/30eb3186daaaf0e06f9ce06307353d98c2831c63/engine.py#L51) when I using multi node and training to the fifth epoch. The gpu utilization will suddenly become 0

![3511610383641_ pic_hd](https://user-images.githubusercontent.com/38682321/104212083-c8afce80-546f-11eb-86b8-49354c5b4347.jpg)

**Comment by fmassa** [comment]
Hi,

Thanks for trying out DeiT.

Given that all other GPUs seem to be spinning at 100%, I suspect that there was a deadlock happening somewhere.

Can you confirm which PyTorch version you are using? Normally debugging deadlocks on distributed are pretty hard, and I can't reproduce the failure in here.

**Comment by pawopawo** [comment]
Thanks

I use PyTorch 1.7.0+ and torchvision 0.8.1+ and timm 0.3.2

**Comment by fmassa** [comment]
Thanks.

So here is what I generally do when I debug such errors:
- find the process id of the job (via htop for example)
- attach gdb to the process via `gdb attach <pid>`
- get backtrace with `thread apply all bt`

You should have a bit stack trace, can you paste it in here?

**Comment by xwjabc** [comment]
I also encounter the same situation (after I modified some part in the model). The stuck usually happens in 4th or 5th epoch. One GPU is 0% and all others are 100%. Actually, in my case, it is because in one GPU process, the loss becomes NaN and the process automatically exits, which causes other GPU processes waiting for this one. 

The current log output is allowed from the main GPU process (set in `utils.py - setup_for_distributed()` ), which ignores the message from other GPU processes. I would suggest enable the log output for all processes. For example:

1. Add another `setup_for_distributed2()` in `utils.py`:
```
def setup_for_distributed2(rank):
    import builtins as __builtin__
    builtin_print = __builtin__.print

    def print(*args, **kwargs):
        builtin_print('[RANK:{}]'.format(rank), *args, **kwargs)

    __builtin__.print = print
```

2. Modify the last line in `def init_distributed_mode(args)`  in `utils.py`
```
def init_distributed_mode(args):
    if 'RANK' in os.environ and 'WORLD_SIZE' in os.environ:
        args.rank = int(os.environ["RANK"])
        args.world_size = int(os.environ['WORLD_SIZE'])
        args.gpu = int(os.environ['LOCAL_RANK'])
    elif 'SLURM_PROCID' in os.environ:
        args.rank = int(os.environ['SLURM_PROCID'])
        args.gpu = args.rank % torch.cuda.device_count()
    else:
        print('Not using distributed mode')
        args.distributed = False
        return

    args.distributed = True

    torch.cuda.set_device(args.gpu)
    args.dist_backend = 'nccl'
    print('| distributed init (rank {}): {}'.format(
        args.rank, args.dist_url), flush=True)
    torch.distributed.init_process_group(backend=args.dist_backend, init_method=args.dist_url,
                                         world_size=args.world_size, rank=args.rank)
    torch.distributed.barrier()
    # setup_for_distributed(args.rank == 0)
    setup_for_distributed2(args.rank)
```

**Comment by changlin31** [comment]
I also encounter the same problem after modifying the model. Training DeiT with patch size 32 may reproduce the problem. In addition to logging errors of all processes, automatically shutting down all other processes would be great.

**Comment by zhoudaquan** [comment]
Hi,

I also encounter the same error when running DDP with one GPU comes into deadlock. Not sure what is the reason for that.

**Comment by dxxz** [comment]
Hi~~ 
I also meet the error with the message when training the DeiT base:
...
Epoch: [7]  [ 190/1251]  eta: 0:14:12  lr: 0.000999  loss: 6.7966 (6.7639)  time: 0.7753  data: 0.0002  max mem: 18018
**Loss is nan, stopping training**
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launch.py", line 260, in <module>
    main()
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launch.py", line 255, in main
    raise subprocess.CalledProcessError(returncode=process.returncode,
subprocess.CalledProcessError: Command '['/opt/conda/bin/python', '-u', 'main.py', '--model', 'deit_base_patch16_224', '--batch-size', '128', '--data-path', '/datasets/torch/imagenet', '--output_dir', 'Results/DeiT-base/Dense_8GPU']' returned non-zero exit status 1.

Any suggestion or workaround for the "Loss is nan, stopping training" error?

**Comment by HubHop** [comment]
Hi @pawopawo , I find you close this issue, have you solved it? In my case, I trained DeiT-base and I also encounter this error. Would you please share your workaround?

**Comment by pawopawo** [comment]
> Hi @pawopawo , I find you close this issue, have you solved it? In my case, I trained DeiT-base and I also encounter this error. Would you please share your workaround?

set new random seed for `DistributedSampler`
