### ISSUE TITLE
no_weight_decay is not called

### ISSUE THREAD

**Issue by changlin31** [facebookresearch/deit#39]
Hi,

I think `VisionTransformer.no_weight_decay()` is not used as intended. 
https://github.com/rwightman/pytorch-image-models/blob/f8463b8fa9c0490db093b36acfce71fa2363b8c3/timm/models/vision_transformer.py#L255

When using `timm`, optimizer should be created before model being wrapped by DDP, because `model.no_weight_decay()` is called when creating optimizer, and DDP doesn't have attribute `no_weight_decay`.
https://github.com/rwightman/pytorch-image-models/blob/f8463b8fa9c0490db093b36acfce71fa2363b8c3/timm/optim/optim_factory.py#L45

```
if hasattr(model, 'no_weight_decay'):
    skip = model.no_weight_decay()
```

Since DDP doesn't have attribute `no_weight_decay`, `model.no_weight_decay()` will not be called in `create_optimizer` and thus weight_decay is applied to all the weights including `{'pos_embed', 'cls_token'}`.

A quick fix could be changing
https://github.com/facebookresearch/deit/blob/30eb3186daaaf0e06f9ce06307353d98c2831c63/main.py#L257
to `optimizer = create_optimizer(args, model_without_ddp)`.
But I'm not sure how fixing this will affect performance, since I have already reproduced the reported performance with your current code.

**Comment by fmassa** [comment]
Hi,

This is a great catch, thanks a lot!

Our original implementation did put the optimizer before the DDP construction, but after a refactoring this issue appeared.

I will run a training to verify how this changes accuracies and I'll report back once training is finished.

**Comment by fmassa** [comment]
Fixed in https://github.com/facebookresearch/deit/pull/52, thanks @changlin31 for spotting this!
