### ISSUE TITLE
Fine-Tuning

### ISSUE THREAD

**Issue by fmahdisoltani** [facebookresearch/deit#41]
Hi, 
Could you add some instructions on how to fine-tune the pretrained model?

Thanks in advance

**Comment by fmassa** [comment]
Hi,

We are adding code for finetuning in https://github.com/facebookresearch/deit/pull/43 , and we will create a new section in the README with pre-trained models and instructions on how to finetune.

**Comment by fmassa** [comment]
Hi,

We've added instructions on how to finetune on different resolutions in #50, let us know if you have any further questions.
