### ISSUE TITLE
OSError: [Errno 105] No buffer space available: 'ImageNet2012/train/n02071294/n02071294_46744.JPEG

### ISSUE THREAD

**Issue by henanjun** [facebookresearch/deit#44]
Hi, I encounter this problem when training tiny-deit on ImageNet
![image](https://user-images.githubusercontent.com/27271981/104541970-9f549580-565d-11eb-99da-8199c99f69f2.png)

**Comment by fmassa** [comment]
Hi,

I don't recall seeing this error in the past. My first guess would be that that you are using too many worker threads for the dataloader

Can you share which PyTorch version are you using?

**Comment by henanjun** [comment]
> Hi,
> 
> I don't recall seeing this error in the past. My first guess would be that that you are using too many worker threads for the dataloader
> 
> Can you share which PyTorch version are you using?
Hi  I am using torch=1.7.0

**Comment by fmassa** [comment]
Thanks. Could you try decreasing the number of dataloader worker threads (by passing `--num_workers 2` for example) and see if you still face this error?

**Comment by henanjun** [comment]
> Thanks. Could you try decreasing the number of dataloader worker threads (by passing `--num_workers 2` for example) and see if you still face this error?

Thanks, I tried --`num_work 4` before. It can solve this problem. But I encounter another problem, the main procedure will be deadlocked during the last several batches of the first epoch. Could you help me? Thanks.

**Comment by TouvronHugo** [comment]
As there is no more activity on this issue, I am closing it, so don't hesitate to reopen it if the problem persists.
