### ISSUE TITLE
failed to load from torch.hub

### ISSUE THREAD

**Issue by ydcjeff** [facebookresearch/deit#58]
AFAIK `torch.hub` needs at least one release to be able to load, since there is no any github release, it has failed to load.

![Screen Shot 2021-01-22 at 21 10 53](https://user-images.githubusercontent.com/32727188/105504831-9bc4ac80-5cf6-11eb-8f81-719b07b57c9f.png)

**Comment by TouvronHugo** [comment]
Hi @ydcjeff,
I think you forgot the `:main`
I just tested `model = torch.hub.load('facebookresearch/deit:main', 'deit_base_patch16_384', pretrained=True)`, it works.
Let me know if that doesn't solve the problem.
Best,
Hugo

**Comment by ydcjeff** [comment]
Hi @TouvronHugo , yes it works now! Thank you.
