### ISSUE TITLE
Can't replicate the validation results

### ISSUE THREAD

**Issue by MichaelSolotky** [facebookresearch/deit#59]
Hi, I'm trying to validate DeiT on the ImageNet validation set and I can't get the same accuracy values as you reported. A launch of ```python main.py --eval --resume https://dl.fbaipublicfiles.com/deit/deit_base_patch16_224-b5f2ef4d.pth --data-path /path/to/imagenet``` gives 80.985% top1 accuracy, while it should be 81.846 according to the tutorial in the README. the ```timm``` version is ```0.3.2``` as it should be. If the code of DeiT is correct then there's only one place for mistakes -- the ImageNet dataset. The class names in the validation folder look as follows ```000 001 ... 999```, which means they are sorted in numerical order. Probably something is wrong with the names. Here's the [val_log.txt](https://github.com/facebookresearch/deit/files/5856606/val_log.txt) file. Have you guys encountered a similar issue? Thanx

**Comment by MichaelSolotky** [comment]
Solved, I've had a wrong version of ImageNet

**Comment by MichaelSolotky** [comment]
> Can you tell me which version of Imagenet you use and where you downloaded it. Thank you very much!

That version wasn't public. And it was created from the official ImageNet using a very sophisticated mechanism that happened to corrupt images. So I can't help you with this

**Comment by duchenzhuang** [comment]
> > Can you tell me which version of Imagenet you use and where you downloaded it. Thank you very much!
> 
> That version wasn't public. And it was created from the official ImageNet using a very sophisticated mechanism that happened to corrupt images. So I can't help you with this

Thank you for answering my question......
