### ISSUE TITLE
evaluation is not running in parallel on multiple gpus

### ISSUE THREAD

**Issue by tfriedel** [facebookresearch/deit#6]
I'm trying out the code with a dataset that has about 190.000 training images and about 81.000 validation images. With a batch size of 64 and 8 GPUs, the progress stats report
372 steps for a training epoch and 
846 steps for an eval epoch.

372\*8\*64=190464
846\*64\*1.5=81216
Also nvidia-smi reports all except one gpu are utilized during the eval step. As a quickfix I just evaluate every 10th epoch now. But it would be great if this could be parallelized.

**Comment by TouvronHugo** [comment]
Hi @tfriedel,
Thank you very much for your suggestion.
I think it would be nice to add a parallelized evaluation in our repo.
Best,
Hugo

**Comment by fmassa** [comment]
Fixed by @changlin31 in https://github.com/facebookresearch/deit/pull/24
