### ISSUE TITLE
Will more epochs achieve higher accuracy?

### ISSUE THREAD

**Issue by LiangHann** [facebookresearch/deit#66]
I notice in your paper, you trained 300 epochs. Is this the best accuracy? or by training more epochs the accuracy will increase?

**Comment by HubHop** [comment]
Hi, I retrained DeiT-tiny with ImageNet. As the plot shows below, the Top 1-Acc increases almost linearly between 70 and 250 epoch then slow down after that. Therefore I think 300 is a reasonable setting as more epochs won't get more gains.
![DeiT-Tiny](https://user-images.githubusercontent.com/20661773/108286150-aa5e9080-71dc-11eb-844a-6d4491369e76.png)

**Comment by TouvronHugo** [comment]
Hi @LiangHann and @HubHop ,
Thanks for your question.
We were able to improve the performance of the DeiT Base by training with 400 epochs (82.2%) but with more epochs the performance saturate.
With distillation we have been able to train with more epochs (1000).
Best,
Hugo
