### ISSUE TITLE
Model_ema

### ISSUE THREAD

**Issue by OmerMagdy** [facebookresearch/deit#67]
Hi,
I can't find any usage for the model_ema in your code since you are training it and just use it at logging , 
So Can I know what is the usage for it since it doesn't affect the original model at all ?
By the way congratulation for the great work .

**Comment by TouvronHugo** [comment]
Hi @OmerMagdy ,
The model ema does not affect the main model. We calculate it to see if it is better than the main model but we decided to  not put any results obtained with the model EMA.
Best,
Hugo
