### ISSUE TITLE
Results on CIFAR10/100 dataset

### ISSUE THREAD

**Issue by zhoudaquan** [facebookresearch/deit#69]
Hi,

Thanks for your amazing works. Can I check if there is a plan to release the training details on small datasets as introduced in the paper, such as CIFAR10/100 and Standford Cars?

Thanks.

**Comment by TouvronHugo** [comment]
Hi @zhoudaquan,
Yes, there is some elements [here](https://github.com/facebookresearch/deit/issues/45#issuecomment-765213622).
Let me know if you want more details.
Best,
Hugo
