### ISSUE TITLE
Distillation instruction w/o using submitit

### ISSUE THREAD

**Issue by lcmeng** [facebookresearch/deit#70]
Hello,

Thank you for sharing the work. Would you please share the instruction for distilling on a single instance? I tried to cook up one, but it doesn't work.

`python -m torch.distributed.launch --nproc_per_node=4 --use_env main.py --model deit_tiny_distilled_patch16_224 --batch-size 256 --data-path ~/workspace/datasets/ILSVRC2012/ --output_dir output_deit_tiny_distilled_patch16_224  --distillation-type hard --teacher-model regnety_160 --teacher-path https://dl.fbaipublicfiles.com/deit/regnety_160-a5fe301d.pth`

TIA!

**Comment by Coorch** [comment]
Hello, 
For me, the next step works:
1. Download the teacher pth(https://dl.fbaipublicfiles.com/deit/regnety_160-a5fe301d.pth) to local;
2. run the script:
```bash
python -m torch.distributed.launch \
--nproc_per_node=8 \
--use_env \
main.py \
--model deit_base_distilled_patch16_224 \
--distillation-type hard \
--teacher-model regnety_160 \
--teacher-path local_path \
--data-path ./data/imagenet \
--output_dir ./checkpoint
```

**Comment by lcmeng** [comment]
Thank you @Coorch ! I followed your suggestion and put together the command below:
```
python -m torch.distributed.launch \
--nproc_per_node=8 \
--use_env \
main.py \
--model deit_tiny_distilled_patch16_224 --epochs 1000 \
--distillation-type hard \
--teacher-model regnety_160 \
--teacher-path ./regnety_160-a5fe301d.pth \
--data-path ~/datasets/ILSVRC2012/ \
--output_dir ./checkpoints/ 
```

Can the authors and developers please confirm this is the right instruction to produce the **DeiT-Ti ⚗ / 1000 epochs with 76.6% top-1** accuracy?

**Comment by TouvronHugo** [comment]
Yes, you just have to make sure that the global batch size is 1024.
