### ISSUE TITLE
Ablation study on training epochs of vanilla DeiT variants

### ISSUE THREAD

**Issue by lcmeng** [facebookresearch/deit#75]
Hi,

Thanks for sharing the amazing work and results! In Table 5 of the paper, it shows a significant accuracy increase between ⚗ models trained with 300 epochs and 1000 epochs, especially for the DeiT-Ti⚗ (+2.1%). Have the authors or anyone else tried training the vanilla DeiT-Ti for more than 300 epochs? Have you seen a significant accuracy jump as the distillation case? TIA

**Comment by TouvronHugo** [comment]
Hi @lcmeng ,
Without distillation the best performance is achieved with 400 epochs (Figure 3 in the paper). 
The models saturate quickly with more epochs.
Best,
Hugo
