### ISSUE TITLE
Reproducing results, imagenet version, imagefolder structure

### ISSUE THREAD

**Issue by fmahdisoltani** [facebookresearch/deit#78]
Hi,

Which imagenet version should be used to reproduce the results in README of this repo?
imagenet 2012 is not structured like ImageFolder.
Evaluating on imagenet 2012 validation set gives ~0 % accuracy.

**Comment by TouvronHugo** [comment]
Hi @fmahdisoltani ,
We use ImageNet 2012 with an ImageFolder structure as described in the README (one subfolder by ImageNet sysnet).
Best,
Hugo
