### ISSUE TITLE
Details of improving performance from 77.9 to 81.8

### ISSUE THREAD

**Issue by ShoufaChen** [facebookresearch/deit#80]
Hi,
@TouvronHugo 
Thanks for releasing the code of this great work. 

I am wondering how does the model goes from Vit-B 77.9 to DeiT-B 81.8.

From https://github.com/facebookresearch/deit/issues/19, I got that the only architecture difference between these two model is  MLP v.s. Single Linear.

However, I do not understand what's the **optimization procedure** mentioned [here](https://github.com/facebookresearch/deit/issues/19#issuecomment-754607873), which causes the significant difference.

**Comment by ShoufaChen** [comment]
Sorry for missing something. 

I guess that the optimization procedure is listed in Table 9 of the paper. Is it right?

Thanks.

**Comment by TouvronHugo** [comment]
Hi @ShoufaChen ,
Yes, that's right
Best,
Hugo
