### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by markgicharu** [facebookresearch/deit#86]
I get this error when I try to run a training loop on my custom dataset:
screenshots below: including environment, error and folder structure; I am thinking the problem is the getting the classes for the folder structure.:
Kindly assist
![image](https://user-images.githubusercontent.com/16897706/114402785-d713a080-9bac-11eb-8b33-67ed13c55f9b.png)
![image](https://user-images.githubusercontent.com/16897706/114402882-f27eab80-9bac-11eb-941a-5fcfb109130c.png)
![image](https://user-images.githubusercontent.com/16897706/114403100-29ed5800-9bad-11eb-89bc-7bf7c7b0b00c.png)
![image](https://user-images.githubusercontent.com/16897706/114403255-4c7f7100-9bad-11eb-8682-401fd181a23e.png)
![image](https://user-images.githubusercontent.com/16897706/114403498-851f4a80-9bad-11eb-91a0-dcefe9b98437.png)
![image](https://user-images.githubusercontent.com/16897706/114409486-2c52b080-9bb3-11eb-9bd5-e35e7187f201.png)

file structure below: its the main folder for Broccolli Classification, then train and val folders then the classes folder with images in per class.

**Comment by TouvronHugo** [comment]
Hi @markgicharu,
Thanks for your question.
If the problem is the number of classes you need to change this part of the [code](https://github.com/facebookresearch/deit/blob/cb29b5efd522a0ac83d64aa8b41fe27cead3a030/datasets.py#L56) to adapt it to your dataset.
Best,
Hugo

**Comment by markgicharu** [comment]
Hello @TouvronHugo Many thanks for the prompt response.
Will try your suggestion and get back to tou once it works.
Thanks again
