### ISSUE TITLE
Will you provide the pretrained model of CaiT-XXS-24 or CaiT-XXS-36?

### ISSUE THREAD

**Issue by JiaDingCN** [facebookresearch/deit#87]
Hi, I have read your CaiT paper and the performance in this paper is very good. I want to learn more about that and the CaiT-XXS model seems suitable to my computer's GPU. But the cait_models.py file in this repository seems do not contain the pretrained model of CaiT-XXS. Do you plan to provide it?
Thanks.

**Comment by TouvronHugo** [comment]
Hi @JiaDingCN ,
Thanks for your message,
I have just added the XXS models with pre-trained weight for resolution 224x224 and 384x384.
Best,
Hugo

**Comment by JiaDingCN** [comment]
It really solves my problem, thank you!
