### ISSUE TITLE
Question about Repeated Augmentation

### ISSUE THREAD

**Issue by moskomule** [facebookresearch/deit#89]
Hi, first of all, thank you for releasing the code base.
I have a small question about the sampler for Repeated Augmentation. What does this `256*256` mean?

https://github.com/facebookresearch/deit/blob/cb29b5efd522a0ac83d64aa8b41fe27cead3a030/samplers.py#L32

Thank you!

**Comment by TouvronHugo** [comment]
Hi @moskomule,
Thanks for your question,
It's just to have an implementation closer to the implementation in [Multigrain](https://github.com/facebookresearch/multigrain).
Best,
Hugo

**Comment by moskomule** [comment]
Hi Hugo, thanks for your reply.
Do you mean https://github.com/facebookresearch/multigrain/blob/master/multigrain/lib/samplers.py?
I couldn't find `256*256` in multigrain's code.
I guess it's something like `batch_size*number_of_nodes` or something.

**Comment by KyleZheng1997** [comment]
I have tried to remove the RAsampler for deit-tiny and deit-small, the performance is almost the same.

**Comment by TouvronHugo** [comment]
Hi @moskomule ,

No it's just to determine the number of images used in the dataset for each epochs.
This is not exactly  `int(math.floor(len(self.dataset) / self.num_replicas)) ` but just the nearest multiple of 256. I think it was originally used for question of batch size.

Best,

Hugo

**Comment by TouvronHugo** [comment]
Hi @KyleZheng1997 ,
Yes I have noticed that, the smaller the model is the more stable it is and therefore some regularization components are less important.
Best,
Hugo

**Comment by moskomule** [comment]
Hi @TouvronHugo, Thank you for clarifying. Best, Ryuichiro.

**Comment by rentainhe** [comment]
> 

which means RASampler is important for model larger than `Base`? I've noticed that RA brings lots of performance for `ViT-Base` Model~
