### ISSUE TITLE
Distillation training setting in DeiT

### ISSUE THREAD

**Issue by JiaDingCN** [facebookresearch/deit#92]
Hi, I am trying to reproduce the distillation result in DeiT peper but I am a little confused about the training detail. In table 2 of the DeiT paper there is 'pretrain' in 'Student: DeiT-B'  column and in table 3 you mentioned '300 epochs of pre-training'. I'm confused about its meaning: pretrain for teacher or student? 

So take table 2 for example, to make DeiT-B achieve 83.1, the teacher model 'RegNetY-16GF' and student model 'DeiT-B' should both be pretrained,or just the teacher model? Would you please share the command to train since it's not included in README file.

Thanks a lot.

**Comment by JiaDingCN** [comment]
Sorry that I find the command in the README file now, it seems my downloaded README file is out of date. I'm only confused about the 'pretrain' meaning in paper now.

**Comment by liubx07** [comment]
It seems that this "pretrain" is under 224 resolution, followed by a finetuning stage under bigger resolution

**Comment by JiaDingCN** [comment]
That makes sense.Thanks.
