### ISSUE TITLE
ViT ImageNet-1K Weights

### ISSUE THREAD

**Issue by RaivoKoot** [facebookresearch/deit#94]
Can you please also provide the weights of the base ViT when trained only on ImageNet 1k?

**Comment by jegou** [comment]
All the weights we provide are for models trained only with image from ImageNet 1k.

Therefore I am not sure to understand your question: we already share the two ViT-B model trained with DeiT procedure, and identified as DeiT-B models (without and with distillation).

**Comment by RaivoKoot** [comment]
Thank you for the prompt reply! Apologies for the misunderstanding. I am wondering whether you have any weights for the base ViT without ANY new training tricks. Specifically, the one labelled "ViT-B" in your acc/speed plot at the top of the README.

In the model zoo table in your README:
From what I understnad the model with name "DeiT-base" that has `acc@1: 81.8%`, `acc@5: 95.6%` and `86M params`, is also trained with some new tricks, right?

**Comment by jegou** [comment]
The ViT-B refers to the Google results, so you should ask them directly. 

My understanding is that the authors of ViT did not share the weights for the Imagenet1k model, and they did not share the initial training code that would allow the reproduction of these results (only the fine-tuning code). Ross Wightman shares the Vit-B weights of google but trained on Imagenet21k, as these were shared at [https://github.com/google-research/vision_transformer].

**Comment by RaivoKoot** [comment]
I see. Thank you very much for the clarification of all that.
