### ISSUE TITLE
Clarification on batch size / repeated augmentation and RASampler

### ISSUE THREAD

**Issue by helia95** [facebookresearch/deit#95]
Hi, thanks for this great repo.

Should the batch size reported in the paper (1024) be interpreted as the number of different samples fed into the model (without considering repeated samples)?

Another question about RASampler. The reason to don't keep all the 3 augmented versions of one sample in a single GPU(and "send" each version to a different one) is due to normalization issues? Does the performance change if we keep all augmented versions in one GPU? What if we increase the number of samples loaded in a single GPU?

**Comment by TouvronHugo** [comment]
Hi @helia95 ,
Thanks for your questions,
No, 1024 is the batch size taking into account the repeated samples.
Yes, this is to avoid normalization issues with Batch-norm with the layer-norm it should have no impact.
I hope I've answered your questions, don't hesitate if you have any other questions.
Best,
Hugo

**Comment by helia95** [comment]
Thanks @TouvronHugo, last question if you don't mind.

Is it possible that repeated augmentation slightly hurts the performances (-0.4%) for DeiT-S?

**Comment by TouvronHugo** [comment]
Yes it's possible, I think repeated augmentation is especially useful for bigger models that need more regularization

**Comment by sigeisler** [comment]
Hi, I have a follow-up question. Can you please explain why you subsample the dataset with the factor `256 * 256` [here](https://github.com/facebookresearch/deit/blob/main/samplers.py#L32)?

**Comment by sigeisler** [comment]
@TouvronHugo should I rather open a separate issue? In case the answer to the qeustion is obvious, it would also be more than sufficient to provide a reference. Thank you!
