### ISSUE TITLE
Training logs

### ISSUE THREAD

**Issue by AlexanderMath** [facebookresearch/deit#96]
Amazing article and code! Are you too busy to share the training logs for the pretrained models? I'm particularly interested in "deit_tiny" and "deit_small". Would take me a week to retrain.

Keep up the great work!

**Comment by TouvronHugo** [comment]
Hi @AlexanderMath ,
Thanks for your question,
There is some training logs here [deit_small](https://gist.github.com/fmassa/0dbd0184a0adb904ef42277b487d8b53) and [deit_base](https://gist.github.com/fmassa/0497ed4e382d5de19b98bb7168815610).
Best,
Hugo
