### ISSUE TITLE
Timeout error during DistributedDataParallel

### ISSUE THREAD

**Issue by Provemj** [facebookresearch/deit#97]
The whole program got stuck at the line of "model = torch.nn.parallel.DistributedDataParallel(model, device_ids=[args.gpu])"

I changed it into DataParallel, it went into the training session but reported the error that tensors should be stored in one device afterwards. 

Looking for help

**Comment by TouvronHugo** [comment]
Hi @Provemj ,
Thanks for your question,
How many gpu do you use? Did you try to launch with submitit?
Best,
Hugo

**Comment by TouvronHugo** [comment]
As there is no more activity I am closing the issue but feel free to re-open it if needed
