### ISSUE TITLE
problem in dataloader coco

### ISSUE THREAD

**Issue by mathshangw** [facebookresearch/deit#98]
I searched and tried this

if not isinstance(dataset_list, (list, tuple)):
        raise RuntimeError(
            "dataset_list should be a list of strings, got {}".format(dataset_list)
        )
    datasets = []
    for dataset_name in dataset_list:
        data = dataset_catalog.get(dataset_name)
        factory = getattr(D, data["factory"])
        args = data["args"]
        # for COCODataset, we want to remove images without annotations
        # during training
        if data["factory"] == "COCODataset":
            args["remove_images_without_annotations"] = is_train
        if data["factory"] == "PascalVOCDataset":
            args["use_difficult"] = not is_train
        args["transforms"] = transforms
        # make dataset from factory
        dataset = factory(**args)
        datasets.append(dataset)

    # for testing, return a list of datasets
    if not is_train:
        return datasets

    # for training, concatenate all datasets into a single one
    dataset = datasets[0]
    if len(datasets) > 1:
        dataset = D.ConcatDataset(datasets)

    return [dataset] 

but got problem with it .. can someone help me ? 
i need to change image net to coco in this class 
https://github.com/facebookresearch/deit/blob/main/datasets.py

exactly in this method 
def build_dataset(is_train, args):

**Comment by TouvronHugo** [comment]
Hi @mathshangw ,
Did you try to build a custom dataset to load COCO the way you want?
When this is done you can very easily add the dataset by doing as we did for iNaturalist.
Best,
Hugo

**Comment by TouvronHugo** [comment]
As there is no more activity I am closing the issue but feel free to re-open it if needed

**Comment by lianxxx** [comment]
> Hi @mathshangw ,
> Did you try to build a custom dataset to load COCO the way you want?
> When this is done you can very easily add the dataset by doing as we did for iNaturalist.
> Best,
> Hugo

The hard distillation looks not applicable to the multi-label classification problem, what would you suggest when applied on a multi-label dataset? Thank you.
