### ISSUE TITLE
ResMLP training code and minor syntax issues

### ISSUE THREAD

**Issue by briancheung** [facebookresearch/deit#99]
Is it possible to reproduce the ResMLP results in the current codebase? 

I noticed there are a few syntax errors in the current 
ResMLP implementation and it's not imported into the main.py.

Here are the syntax errors found so far:

https://github.com/facebookresearch/deit/blob/6fa7ef60b4144b1e78f2cdb05598dce950e16ba6/resmlp_models.py#L176
https://github.com/facebookresearch/deit/blob/6fa7ef60b4144b1e78f2cdb05598dce950e16ba6/resmlp_models.py#L25
https://github.com/facebookresearch/deit/blob/6fa7ef60b4144b1e78f2cdb05598dce950e16ba6/resmlp_models.py#L43

**Comment by TouvronHugo** [comment]
Hi @briancheung ,
Thank you for pointing out the errors normally I have corrected them.
It is possible to reproduce the results of ResMLP with the current codebase, just import the models into main.py
Best,
Hugo

**Comment by briancheung** [comment]
There may be some missing imports as well

`NameError: name 'DropPath' is not defined`

**Comment by TouvronHugo** [comment]
Normally it's corrected
Best,
Hugo
